// 195 countries: 193 UN member states + Vatican City + Palestine
const COUNTRY_DATA: { name: string; accept: string[] }[] = [
  { name: 'Afghanistan',                      accept: ['afghanistan'] },
  { name: 'Albania',                          accept: ['albania'] },
  { name: 'Algeria',                          accept: ['algeria'] },
  { name: 'Andorra',                          accept: ['andorra'] },
  { name: 'Angola',                           accept: ['angola'] },
  { name: 'Antigua and Barbuda',              accept: ['antigua and barbuda', 'antigua', 'barbuda'] },
  { name: 'Argentina',                        accept: ['argentina'] },
  { name: 'Armenia',                          accept: ['armenia'] },
  { name: 'Australia',                        accept: ['australia'] },
  { name: 'Austria',                          accept: ['austria'] },
  { name: 'Azerbaijan',                       accept: ['azerbaijan'] },
  { name: 'Bahamas',                          accept: ['bahamas', 'the bahamas'] },
  { name: 'Bahrain',                          accept: ['bahrain'] },
  { name: 'Bangladesh',                       accept: ['bangladesh'] },
  { name: 'Barbados',                         accept: ['barbados'] },
  { name: 'Belarus',                          accept: ['belarus'] },
  { name: 'Belgium',                          accept: ['belgium'] },
  { name: 'Belize',                           accept: ['belize'] },
  { name: 'Benin',                            accept: ['benin'] },
  { name: 'Bhutan',                           accept: ['bhutan'] },
  { name: 'Bolivia',                          accept: ['bolivia'] },
  { name: 'Bosnia and Herzegovina',           accept: ['bosnia and herzegovina', 'bosnia', 'herzegovina', 'bosnia-herzegovina'] },
  { name: 'Botswana',                         accept: ['botswana'] },
  { name: 'Brazil',                           accept: ['brazil', 'brasil'] },
  { name: 'Brunei',                           accept: ['brunei', 'brunei darussalam'] },
  { name: 'Bulgaria',                         accept: ['bulgaria'] },
  { name: 'Burkina Faso',                     accept: ['burkina faso', 'burkina'] },
  { name: 'Burundi',                          accept: ['burundi'] },
  { name: 'Cape Verde',                       accept: ['cape verde', 'cabo verde'] },
  { name: 'Cambodia',                         accept: ['cambodia', 'kampuchea'] },
  { name: 'Cameroon',                         accept: ['cameroon'] },
  { name: 'Canada',                           accept: ['canada'] },
  { name: 'Central African Republic',         accept: ['central african republic', 'car', 'central africa'] },
  { name: 'Chad',                             accept: ['chad'] },
  { name: 'Chile',                            accept: ['chile'] },
  { name: 'China',                            accept: ['china', "people's republic of china", 'prc'] },
  { name: 'Colombia',                         accept: ['colombia'] },
  { name: 'Comoros',                          accept: ['comoros'] },
  { name: 'DR Congo',                         accept: ['dr congo', 'democratic republic of the congo', 'democratic republic of congo', 'drc', 'congo dr', 'congo democratic republic', 'zaire'] },
  { name: 'Republic of the Congo',            accept: ['republic of the congo', 'republic of congo', 'congo republic', 'congo-brazzaville', 'brazzaville'] },
  { name: 'Costa Rica',                       accept: ['costa rica'] },
  { name: 'Croatia',                          accept: ['croatia'] },
  { name: 'Cuba',                             accept: ['cuba'] },
  { name: 'Cyprus',                           accept: ['cyprus'] },
  { name: 'Czech Republic',                   accept: ['czech republic', 'czechia', 'czech'] },
  { name: 'Denmark',                          accept: ['denmark'] },
  { name: 'Djibouti',                         accept: ['djibouti'] },
  { name: 'Dominica',                         accept: ['dominica'] },
  { name: 'Dominican Republic',               accept: ['dominican republic'] },
  { name: 'Ecuador',                          accept: ['ecuador'] },
  { name: 'Egypt',                            accept: ['egypt'] },
  { name: 'El Salvador',                      accept: ['el salvador', 'salvador'] },
  { name: 'Equatorial Guinea',                accept: ['equatorial guinea'] },
  { name: 'Eritrea',                          accept: ['eritrea'] },
  { name: 'Estonia',                          accept: ['estonia'] },
  { name: 'Eswatini',                         accept: ['eswatini', 'swaziland'] },
  { name: 'Ethiopia',                         accept: ['ethiopia'] },
  { name: 'Fiji',                             accept: ['fiji'] },
  { name: 'Finland',                          accept: ['finland'] },
  { name: 'France',                           accept: ['france'] },
  { name: 'Gabon',                            accept: ['gabon'] },
  { name: 'Gambia',                           accept: ['gambia', 'the gambia'] },
  { name: 'Georgia',                          accept: ['georgia'] },
  { name: 'Germany',                          accept: ['germany'] },
  { name: 'Ghana',                            accept: ['ghana'] },
  { name: 'Greece',                           accept: ['greece'] },
  { name: 'Grenada',                          accept: ['grenada'] },
  { name: 'Guatemala',                        accept: ['guatemala'] },
  { name: 'Guinea',                           accept: ['guinea'] },
  { name: 'Guinea-Bissau',                    accept: ['guinea-bissau', 'guinea bissau'] },
  { name: 'Guyana',                           accept: ['guyana'] },
  { name: 'Haiti',                            accept: ['haiti'] },
  { name: 'Honduras',                         accept: ['honduras'] },
  { name: 'Hungary',                          accept: ['hungary'] },
  { name: 'Iceland',                          accept: ['iceland'] },
  { name: 'India',                            accept: ['india'] },
  { name: 'Indonesia',                        accept: ['indonesia'] },
  { name: 'Iran',                             accept: ['iran', 'islamic republic of iran'] },
  { name: 'Iraq',                             accept: ['iraq'] },
  { name: 'Ireland',                          accept: ['ireland', 'republic of ireland'] },
  { name: 'Israel',                           accept: ['israel'] },
  { name: 'Italy',                            accept: ['italy'] },
  { name: 'Ivory Coast',                      accept: ['ivory coast', "cote d'ivoire", 'côte d\'ivoire', 'cote divoire'] },
  { name: 'Jamaica',                          accept: ['jamaica'] },
  { name: 'Japan',                            accept: ['japan'] },
  { name: 'Jordan',                           accept: ['jordan'] },
  { name: 'Kazakhstan',                       accept: ['kazakhstan'] },
  { name: 'Kenya',                            accept: ['kenya'] },
  { name: 'Kiribati',                         accept: ['kiribati'] },
  { name: 'Kuwait',                           accept: ['kuwait'] },
  { name: 'Kyrgyzstan',                       accept: ['kyrgyzstan', 'kyrgyz republic'] },
  { name: 'Laos',                             accept: ['laos', 'lao', 'lao pdr'] },
  { name: 'Latvia',                           accept: ['latvia'] },
  { name: 'Lebanon',                          accept: ['lebanon'] },
  { name: 'Lesotho',                          accept: ['lesotho'] },
  { name: 'Liberia',                          accept: ['liberia'] },
  { name: 'Libya',                            accept: ['libya'] },
  { name: 'Liechtenstein',                    accept: ['liechtenstein'] },
  { name: 'Lithuania',                        accept: ['lithuania'] },
  { name: 'Luxembourg',                       accept: ['luxembourg'] },
  { name: 'Madagascar',                       accept: ['madagascar'] },
  { name: 'Malawi',                           accept: ['malawi'] },
  { name: 'Malaysia',                         accept: ['malaysia'] },
  { name: 'Maldives',                         accept: ['maldives'] },
  { name: 'Mali',                             accept: ['mali'] },
  { name: 'Malta',                            accept: ['malta'] },
  { name: 'Marshall Islands',                 accept: ['marshall islands'] },
  { name: 'Mauritania',                       accept: ['mauritania'] },
  { name: 'Mauritius',                        accept: ['mauritius'] },
  { name: 'Mexico',                           accept: ['mexico'] },
  { name: 'Micronesia',                       accept: ['micronesia', 'federated states of micronesia', 'fsm'] },
  { name: 'Moldova',                          accept: ['moldova', 'republic of moldova'] },
  { name: 'Monaco',                           accept: ['monaco'] },
  { name: 'Mongolia',                         accept: ['mongolia'] },
  { name: 'Montenegro',                       accept: ['montenegro'] },
  { name: 'Morocco',                          accept: ['morocco'] },
  { name: 'Mozambique',                       accept: ['mozambique'] },
  { name: 'Myanmar',                          accept: ['myanmar', 'burma'] },
  { name: 'Namibia',                          accept: ['namibia'] },
  { name: 'Nauru',                            accept: ['nauru'] },
  { name: 'Nepal',                            accept: ['nepal'] },
  { name: 'Netherlands',                      accept: ['netherlands', 'holland', 'the netherlands'] },
  { name: 'New Zealand',                      accept: ['new zealand', 'nz'] },
  { name: 'Nicaragua',                        accept: ['nicaragua'] },
  { name: 'Niger',                            accept: ['niger'] },
  { name: 'Nigeria',                          accept: ['nigeria'] },
  { name: 'North Korea',                      accept: ['north korea', 'dprk', 'democratic peoples republic of korea'] },
  { name: 'North Macedonia',                  accept: ['north macedonia', 'macedonia'] },
  { name: 'Norway',                           accept: ['norway'] },
  { name: 'Oman',                             accept: ['oman'] },
  { name: 'Pakistan',                         accept: ['pakistan'] },
  { name: 'Palau',                            accept: ['palau'] },
  { name: 'Palestine',                        accept: ['palestine', 'palestinian territories', 'west bank', 'gaza'] },
  { name: 'Panama',                           accept: ['panama'] },
  { name: 'Papua New Guinea',                 accept: ['papua new guinea', 'png'] },
  { name: 'Paraguay',                         accept: ['paraguay'] },
  { name: 'Peru',                             accept: ['peru'] },
  { name: 'Philippines',                      accept: ['philippines'] },
  { name: 'Poland',                           accept: ['poland'] },
  { name: 'Portugal',                         accept: ['portugal'] },
  { name: 'Qatar',                            accept: ['qatar'] },
  { name: 'Romania',                          accept: ['romania'] },
  { name: 'Russia',                           accept: ['russia', 'russian federation'] },
  { name: 'Rwanda',                           accept: ['rwanda'] },
  { name: 'Saint Kitts and Nevis',            accept: ['saint kitts and nevis', 'st kitts and nevis', 'saint kitts', 'st kitts', 'st. kitts'] },
  { name: 'Saint Lucia',                      accept: ['saint lucia', 'st lucia', 'st. lucia'] },
  { name: 'Saint Vincent and the Grenadines', accept: ['saint vincent and the grenadines', 'st vincent', 'saint vincent', 'st. vincent'] },
  { name: 'Samoa',                            accept: ['samoa', 'western samoa'] },
  { name: 'San Marino',                       accept: ['san marino'] },
  { name: 'São Tomé and Príncipe',            accept: ['são tomé and príncipe', 'sao tome and principe', 'sao tome', 'são tomé'] },
  { name: 'Saudi Arabia',                     accept: ['saudi arabia', 'saudi'] },
  { name: 'Senegal',                          accept: ['senegal'] },
  { name: 'Serbia',                           accept: ['serbia'] },
  { name: 'Seychelles',                       accept: ['seychelles'] },
  { name: 'Sierra Leone',                     accept: ['sierra leone'] },
  { name: 'Singapore',                        accept: ['singapore'] },
  { name: 'Slovakia',                         accept: ['slovakia'] },
  { name: 'Slovenia',                         accept: ['slovenia'] },
  { name: 'Solomon Islands',                  accept: ['solomon islands'] },
  { name: 'Somalia',                          accept: ['somalia'] },
  { name: 'South Africa',                     accept: ['south africa'] },
  { name: 'South Korea',                      accept: ['south korea', 'republic of korea', 'korea'] },
  { name: 'South Sudan',                      accept: ['south sudan'] },
  { name: 'Spain',                            accept: ['spain'] },
  { name: 'Sri Lanka',                        accept: ['sri lanka', 'ceylon'] },
  { name: 'Sudan',                            accept: ['sudan'] },
  { name: 'Suriname',                         accept: ['suriname', 'surinam'] },
  { name: 'Sweden',                           accept: ['sweden'] },
  { name: 'Switzerland',                      accept: ['switzerland'] },
  { name: 'Syria',                            accept: ['syria'] },
  { name: 'Tajikistan',                       accept: ['tajikistan'] },
  { name: 'Tanzania',                         accept: ['tanzania'] },
  { name: 'Thailand',                         accept: ['thailand', 'siam'] },
  { name: 'Timor-Leste',                      accept: ['timor-leste', 'east timor', 'timor leste'] },
  { name: 'Togo',                             accept: ['togo'] },
  { name: 'Tonga',                            accept: ['tonga'] },
  { name: 'Trinidad and Tobago',              accept: ['trinidad and tobago', 'trinidad', 'tobago'] },
  { name: 'Tunisia',                          accept: ['tunisia'] },
  { name: 'Turkey',                           accept: ['turkey', 'türkiye', 'turkiye'] },
  { name: 'Turkmenistan',                     accept: ['turkmenistan'] },
  { name: 'Tuvalu',                           accept: ['tuvalu'] },
  { name: 'Uganda',                           accept: ['uganda'] },
  { name: 'Ukraine',                          accept: ['ukraine'] },
  { name: 'United Arab Emirates',             accept: ['united arab emirates', 'uae'] },
  { name: 'United Kingdom',                   accept: ['united kingdom', 'uk', 'great britain', 'britain'] },
  { name: 'United States',                    accept: ['united states', 'usa', 'us', 'united states of america', 'america'] },
  { name: 'Uruguay',                          accept: ['uruguay'] },
  { name: 'Uzbekistan',                       accept: ['uzbekistan'] },
  { name: 'Vanuatu',                          accept: ['vanuatu'] },
  { name: 'Vatican City',                     accept: ['vatican city', 'vatican', 'holy see'] },
  { name: 'Venezuela',                        accept: ['venezuela'] },
  { name: 'Vietnam',                          accept: ['vietnam', 'viet nam'] },
  { name: 'Yemen',                            accept: ['yemen'] },
  { name: 'Zambia',                           accept: ['zambia'] },
  { name: 'Zimbabwe',                         accept: ['zimbabwe'] },
];

const COUNTRY_MAP = new Map<string, string>();
COUNTRY_DATA.forEach(c => c.accept.forEach(a => COUNTRY_MAP.set(a, c.name)));

export const COUNTRIES = COUNTRY_DATA.map(c => c.name);

export const COUNTRY_SECTIONS: { header: string; countries: string[] }[] = [
  { header: 'Africa', countries: [
    'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde',
    'Central African Republic', 'Chad', 'Comoros', 'DR Congo', 'Republic of the Congo', 'Djibouti',
    'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana',
    'Guinea', 'Guinea-Bissau', 'Ivory Coast', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar',
    'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger',
    'Nigeria', 'Rwanda', 'São Tomé and Príncipe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia',
    'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe',
  ]},
  { header: 'Asia', countries: [
    'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia',
    'China', 'Cyprus', 'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan',
    'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia',
    'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestine', 'Philippines', 'Qatar',
    'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand',
    'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen',
  ]},
  { header: 'Europe', countries: [
    'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria',
    'Croatia', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
    'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland',
    'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain',
    'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom', 'Vatican City',
  ]},
  { header: 'North America', countries: [
    'Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica', 'Cuba',
    'Dominica', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti', 'Honduras',
    'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Saint Kitts and Nevis', 'Saint Lucia',
    'Saint Vincent and the Grenadines', 'Trinidad and Tobago', 'United States',
  ]},
  { header: 'South America', countries: [
    'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay',
    'Peru', 'Suriname', 'Uruguay', 'Venezuela',
  ]},
  { header: 'Oceania', countries: [
    'Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Nauru', 'New Zealand',
    'Palau', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu',
  ]},
];

export function matchCountry(guess: string): string | null {
  return COUNTRY_MAP.get(guess.trim().toLowerCase()) ?? null;
}
