const COUNTRY_DATA: { name: string; accept: string[] }[] = [
  { name: 'Algeria',                  accept: ['algeria'] },
  { name: 'Angola',                   accept: ['angola'] },
  { name: 'Benin',                    accept: ['benin'] },
  { name: 'Botswana',                 accept: ['botswana'] },
  { name: 'Burkina Faso',             accept: ['burkina faso', 'burkina'] },
  { name: 'Burundi',                  accept: ['burundi'] },
  { name: 'Cameroon',                 accept: ['cameroon'] },
  { name: 'Cape Verde',               accept: ['cape verde', 'cabo verde'] },
  { name: 'Central African Republic', accept: ['central african republic', 'car', 'central africa'] },
  { name: 'Chad',                     accept: ['chad'] },
  { name: 'Comoros',                  accept: ['comoros'] },
  { name: 'DR Congo',                 accept: ['dr congo', 'democratic republic of the congo', 'democratic republic of congo', 'drc', 'congo dr', 'congo democratic republic', 'zaire'] },
  { name: 'Republic of the Congo',    accept: ['republic of the congo', 'republic of congo', 'congo republic', 'congo-brazzaville', 'brazzaville'] },
  { name: 'Djibouti',                 accept: ['djibouti'] },
  { name: 'Egypt',                    accept: ['egypt'] },
  { name: 'Equatorial Guinea',        accept: ['equatorial guinea'] },
  { name: 'Eritrea',                  accept: ['eritrea'] },
  { name: 'Eswatini',                 accept: ['eswatini', 'swaziland'] },
  { name: 'Ethiopia',                 accept: ['ethiopia'] },
  { name: 'Gabon',                    accept: ['gabon'] },
  { name: 'Gambia',                   accept: ['gambia', 'the gambia'] },
  { name: 'Ghana',                    accept: ['ghana'] },
  { name: 'Guinea',                   accept: ['guinea'] },
  { name: 'Guinea-Bissau',            accept: ['guinea-bissau', 'guinea bissau'] },
  { name: 'Ivory Coast',              accept: ['ivory coast', "cote d'ivoire", "côte d'ivoire", 'cote divoire'] },
  { name: 'Kenya',                    accept: ['kenya'] },
  { name: 'Lesotho',                  accept: ['lesotho'] },
  { name: 'Liberia',                  accept: ['liberia'] },
  { name: 'Libya',                    accept: ['libya'] },
  { name: 'Madagascar',               accept: ['madagascar'] },
  { name: 'Malawi',                   accept: ['malawi'] },
  { name: 'Mali',                     accept: ['mali'] },
  { name: 'Mauritania',               accept: ['mauritania'] },
  { name: 'Mauritius',                accept: ['mauritius'] },
  { name: 'Morocco',                  accept: ['morocco'] },
  { name: 'Mozambique',               accept: ['mozambique'] },
  { name: 'Namibia',                  accept: ['namibia'] },
  { name: 'Niger',                    accept: ['niger'] },
  { name: 'Nigeria',                  accept: ['nigeria'] },
  { name: 'Rwanda',                   accept: ['rwanda'] },
  { name: 'São Tomé and Príncipe',    accept: ['são tomé and príncipe', 'sao tome and principe', 'sao tome', 'são tomé'] },
  { name: 'Senegal',                  accept: ['senegal'] },
  { name: 'Seychelles',               accept: ['seychelles'] },
  { name: 'Sierra Leone',             accept: ['sierra leone'] },
  { name: 'Somalia',                  accept: ['somalia'] },
  { name: 'South Africa',             accept: ['south africa'] },
  { name: 'South Sudan',              accept: ['south sudan'] },
  { name: 'Sudan',                    accept: ['sudan'] },
  { name: 'Tanzania',                 accept: ['tanzania'] },
  { name: 'Togo',                     accept: ['togo'] },
  { name: 'Tunisia',                  accept: ['tunisia'] },
  { name: 'Uganda',                   accept: ['uganda'] },
  { name: 'Zambia',                   accept: ['zambia'] },
  { name: 'Zimbabwe',                 accept: ['zimbabwe'] },
];

const COUNTRY_MAP = new Map<string, string>();
COUNTRY_DATA.forEach(c => c.accept.forEach(a => COUNTRY_MAP.set(a, c.name)));

export const COUNTRIES_AFRICA = COUNTRY_DATA.map(c => c.name);

export function matchCountry(guess: string): string | null {
  return COUNTRY_MAP.get(guess.trim().toLowerCase()) ?? null;
}
