export const MUSCLES: string[] = [
  // Head & face
  'Frontalis',
  'Orbicularis oculi',
  'Orbicularis oris',
  'Zygomaticus major',
  'Masseter',
  'Temporalis',
  'Buccinator',
  'Platysma',
  'Digastric',
  // Neck
  'Sternocleidomastoid',
  'Scalenus anterior',
  'Scalenus medius',
  'Scalenus posterior',
  'Longus colli',
  'Longus capitis',
  // Back
  'Trapezius',
  'Latissimus dorsi',
  'Rhomboid major',
  'Rhomboid minor',
  'Levator scapulae',
  'Erector spinae',
  'Multifidus',
  'Serratus anterior',
  'Quadratus lumborum',
  'Semispinalis',
  // Chest & shoulder
  'Pectoralis major',
  'Pectoralis minor',
  'Deltoid',
  'Supraspinatus',
  'Infraspinatus',
  'Teres minor',
  'Teres major',
  'Subscapularis',
  // Upper arm
  'Biceps brachii',
  'Brachialis',
  'Coracobrachialis',
  'Triceps brachii',
  // Forearm
  'Brachioradialis',
  'Pronator teres',
  'Pronator quadratus',
  'Supinator',
  'Flexor carpi radialis',
  'Flexor carpi ulnaris',
  'Palmaris longus',
  'Flexor digitorum superficialis',
  'Flexor digitorum profundus',
  'Extensor carpi radialis longus',
  'Extensor carpi radialis brevis',
  'Extensor digitorum',
  // Abdomen & core
  'Rectus abdominis',
  'External oblique',
  'Internal oblique',
  'Transversus abdominis',
  'Diaphragm',
  // Hip & glutes
  'Gluteus maximus',
  'Gluteus medius',
  'Gluteus minimus',
  'Piriformis',
  'Psoas major',
  'Iliacus',
  'Tensor fasciae latae',
  // Thigh
  'Sartorius',
  'Rectus femoris',
  'Vastus lateralis',
  'Vastus medialis',
  'Vastus intermedius',
  'Gracilis',
  'Pectineus',
  'Adductor longus',
  'Adductor brevis',
  'Adductor magnus',
  'Biceps femoris',
  'Semitendinosus',
  'Semimembranosus',
  // Leg
  'Gastrocnemius',
  'Soleus',
  'Plantaris',
  'Popliteus',
  'Tibialis anterior',
  'Tibialis posterior',
  'Fibularis longus',
  'Fibularis brevis',
  'Extensor digitorum longus',
  'Extensor hallucis longus',
  'Flexor digitorum longus',
  'Flexor hallucis longus',
];

const MUSCLES_MAP = new Map(MUSCLES.map(m => [m.toLowerCase(), m]));

export function matchMuscle(guess: string): string | null {
  return MUSCLES_MAP.get(guess.trim().toLowerCase()) ?? null;
}
